-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema".claim
(
    id integer NOT NULL,
    found_id integer NOT NULL,
    user_id integer NOT NULL,
    claim_date date NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    CONSTRAINT claim_pkey PRIMARY KEY (id),
    UNIQUE (user_id),
    UNIQUE (found_id)
);

CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema".found_report
(
    id integer NOT NULL,
    staff_id integer NOT NULL,
    category_id integer NOT NULL,
    item_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    found_date date NOT NULL,
    found_location character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'stored'::character varying,
    created_at date NOT NULL,
    CONSTRAINT found_report_pkey PRIMARY KEY (id),
    UNIQUE (category_id)
);

CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema".item_category
(
    id integer NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT item_category_pkey PRIMARY KEY (id),
    CONSTRAINT name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema".lost_report
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    item_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    lost_date date NOT NULL,
    lost_location character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'stored'::character varying,
    created_at date NOT NULL,
    CONSTRAINT lost_report_pkey PRIMARY KEY (id),
    UNIQUE (category_id)
);

CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema".match
(
    id integer NOT NULL,
    lost_id integer NOT NULL,
    found_id integer NOT NULL,
    score integer NOT NULL,
    date date NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    CONSTRAINT match_pkey PRIMARY KEY (id),
    UNIQUE (lost_id),
    UNIQUE (found_id)
);

CREATE TABLE IF NOT EXISTS "lost-and-found-item-db-schema"."user"
(
    id integer NOT NULL,
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'student'::character varying,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT email UNIQUE (email)
);

ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".claim
    ADD FOREIGN KEY (user_id)
    REFERENCES "lost-and-found-item-db-schema"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".claim
    ADD FOREIGN KEY (found_id)
    REFERENCES "lost-and-found-item-db-schema".found_report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".found_report
    ADD FOREIGN KEY (staff_id)
    REFERENCES "lost-and-found-item-db-schema"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".found_report
    ADD FOREIGN KEY (category_id)
    REFERENCES "lost-and-found-item-db-schema".item_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".lost_report
    ADD FOREIGN KEY (user_id)
    REFERENCES "lost-and-found-item-db-schema"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".lost_report
    ADD FOREIGN KEY (category_id)
    REFERENCES "lost-and-found-item-db-schema".item_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".match
    ADD FOREIGN KEY (lost_id)
    REFERENCES "lost-and-found-item-db-schema".lost_report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "lost-and-found-item-db-schema".match
    ADD FOREIGN KEY (found_id)
    REFERENCES "lost-and-found-item-db-schema".found_report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;